### PR TITLE
Add a new device to support RGB on Ultra Pro devices

### PR DESCRIPTION
**Pull request by spearway**
I need this new device to enable the management of the 24ch Ultra Pro as 6 RGBW channels

### CODE REVIEW

**Comment by Fensterbank** [comment]
Hello @spearway and thank you for your pull request. 
I just force pushed an update to your branch, so that the original format (tab size 4, not spaces) is preserved. Otherwise we would mess up the diff a bit.
If you work on your branch, please make a `git pull` first.

Can you please explain, what you tried to achieve with `channelgoups`.
Not only is this misspelled, such a property is not used anywhere in code.

**Comment by bluemaex** [comment]
@Fensterbank I think I know for what that property is :)

I just saw that @spearway also did a Pull Request to the Homebridge-DMXUniverse Plugin to control those Lights via HomeKit - That is where this property is used. 
(Sorry, I did not find time to review it yet, but I will try to do it this this week.)

**Comment by spearway** [comment]
Sorry yes I needed that for creating the right accessories in home bridge. I got it working very nicely in home kit.

**Comment by Fensterbank** [comment]
Thanks for clarification. Looks fine so far.
Merged! 🍪

**Pull request merged**
