### PR TITLE
Remove deprecated Buffer API for NULL driver and EnttecUSBDMXPRO driver

### PR DESCRIPTION
**Pull request by pboyd04**
The Buffer constructor has been deprecated. This switches to newer node versions using Buffer.alloc and Buffer.from

### CODE REVIEW

**Comment by bluemaex** [comment]
I am eager to merge this, but I want to avoid that we have one driver file using the old API and the other one the new. Do you mind updating the others too?

I can't test this PR in real production because I do not have an enttec :/

**Comment by pboyd04** [comment]
The reason I didn't update the others is that I didn't have anything to test them against. I'll take a pass at it.

**Comment by bluemaex** [comment]
Thats a very valid point. I'll take a look at the dmx4all device, that is what I am using. Don't know what @wiedi and @Fensterbank are using - maybe we can fix them all together :)

**Comment by wiedi** [comment]
Thanks for working on this!

I'm not a fan of all the duplicate code.
I think it would be better to have some compat shim that handles Buffer instantiation for both versions or let's just say that the minimum required version is node 5.10.

Already in this PR there are errors in the legacy code (e.g. using `.from`) and it will only rot more with future changes where adjusting one half will be forgotten.

Is node 5.10 something that we can require people to run e.g. also on older raspberries?

**Comment by pboyd04** [comment]
@wiedi Here is a polyfill you could add as a dependency and get rid of the if's... I'm not sure what versions of node run on original pi's. https://www.npmjs.com/package/buffer-v6-polyfill

**Comment by pboyd04** [comment]
I can't find any restrictions on node version even on old Pi's. So I think we'd probably be pretty safe setting the minimum version. And if someone complains then you can grab a polyfill and crank the version back down. Right now the serialport stuff already puts us a minimum version of 4. One Major version up doesn't seem that bad to me.

**Comment by Fensterbank** [comment]
> Don't know what wiedi and Fensterbank are using - maybe we can fix them all together :)

I'm using Enttec USB DMX PRO too, so I could only test this, not the others.

> Is node 5.10 something that we can require people to run e.g. also on older raspberries?

I don't think there are any difficulties to run new node version on older devices.
Current versions are Node 8 LTS and Node 10, while Node 6 is in Maintenance and reaches the End-of-life in April 2019, see [here](https://github.com/nodejs/Release).

Since Node 5 reached End-of-life and is not safe to use anymore, it would be perfectly fine to set the minimum required node version to 6.x (or even higher)

**Comment by wiedi** [comment]
Sounds good, and the latest patch looks much cleaner. Thanks!

**Comment by Fensterbank** [comment]
Obsolete by PR #61 which has cleaner code.

**Pull request closed without merging**
