### PR TITLE
Update codebase to recover compatibility

### LINKED ISSUE #25: Not working on node version 7.x.x
I'm running this in node 6.9.4 and I get the following in the terminal on running the script.

```
... Output above...

==== C stack trace ===============================

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: SerialportPoller::Init(v8::Local<v8::Object>)
 3: init
 4: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 7: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 8: 0x3310d7e092a7
 9: 0x3310d7f77244
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================
... Output below ...

```

I'm guessing that there is some piece of a dependency that node-dmx uses `v8::ObjectTemplate::Set()`. How can I help find the corresponding dependency and see if there is an update to get node-dmx working in node v7.x.x?

### PR DESCRIPTION
**Pull request by Fensterbank**
This pull request merges relevant commits from another fork to the main repository.
Source code is updated to ES2015+ and the packages are updated to the latest major version to recover compatibility with Node 7+.

Merging this pull request fixes #25 and makes #31 and #32 obsolete.

### CODE REVIEW

**Comment by Fensterbank** [comment]
missed a few things.

**Comment by Fensterbank** [comment]
now all things are done and the PR is ready to merge.
@wiedi would you please check this and the other pull requests?

**Comment by wiedi** [comment]
Hi, thanks for picking this up and apologies for the delay!

There's a lot going on in this PR.

- devices.js looks fine
- if we'd decide to ship an example `dmx-web.json` maybe better to rename the existing one?
- package.json - should not change the url, why is color-convert a dev-dependency?
- pliabAnim.js - what does "pliab" stand for? Maybe this deserves a note/example in the readme?

**Comment by Fensterbank** [comment]
Oh, yes. You're right.
It seems with the commits of thomfort we have a few more wird things we don't want or need. I did not notice this.
I think I will recreate my branch by concentrating on package upgrades and ignoring the other commits from thomfort. Stay tuned...

**Comment by Fensterbank** [comment]
Obsolete

**Pull request closed without merging**
