### PR TITLE
Added support for defining devices in config file

### PR DESCRIPTION
**Pull request by spearway**
This enables the definition of new devices in the config file making it easier to test new devices.

### CODE REVIEW

**Comment by spearway** [comment]
[https://github.com/wiedi/node-dmx/issues/50](url)

**Comment by Fensterbank** [comment]
@spearway I don't really understand you're changes in `dmx.js`.
This change in`dmx-web.js` makes sense, because you now pass the config file to the `DMX` constructor in the web ui.
https://github.com/wiedi/node-dmx/pull/64/files?utf8=%E2%9C%93&diff=unified#diff-c9e5ae1e07767abf86038db8a691fed8R26

But the changes in `dmx.js` aren't clear for me, there is no real functional change, instead `anim.js` is required two times now and is available with `DMX.Animation` and `new DMX().animation`.
I don't see the point.

**Comment by spearway** [comment]
The purpose is to ensure that we can override the device definition in the config file but that we do not remove any existing one doing this. In practice we can augment the device definition or override it but any existing device definition in devices is always there.

There may be an easier way of doing this but it is the intent.

**Comment by Fensterbank** [comment]
Thanks for explanation.
Seems good to me.
Merged. Thanks! 🍪

**Pull request merged**
