### PR TITLE
Enttec Open USB fixed.

### PR DESCRIPTION
**Pull request by FabianBach**
Now all channels are working, not first channel only.

 - edge module is loading the FTDI driver library
 - FTDI drivers required
 - .NET Framework (Windows) or Mono (Unix) required

 Tested with Enttec Open DMX with FT232R USB UART.

### CODE REVIEW

**Comment by wiedi** [comment]
Hi, thanks for doing this. But I am not sure adding a dependency on .NET is a good idea.
I also don't see how that .net code is doing something that can't be done with the ftdi bindings from node.js. If there are actual issues with the ftdi driver I think it might be better to fix those.

**Comment by wiedi** [comment]
I've reworked the enttec open usb driver a bit and have one user reporting that timings are a bit better now.
As I don't have such a device I can't really test it. So feedback is appreciated.
Maybe this also resolves your issue. If not feel free to reopen.

**Comment by FabianBach** [comment]
I just tried to get it to work, but it still does the same as it did before:
Channel 1 is set to 255, no matter which channel and which value I try 
to set.
So it still does not work at all for me.

It is very interresting it seems to work for some other user.
Could you ask that user to contact me or tell me how to contact him?
I would like to find out what the difference is.

Thanks in advance!
Fabian

Am 15.05.2015 um 15:06 schrieb Sebastian Wiedenroth:

**Comment by wiedi** [comment]
Thanks for testing again.

I now understand the device a bit better and see how the current code can't be correct.
What is missing is sending a serial break (which your code does). Sadly the node-ftdi module is indeed missing that functionality. I'll see if i can get that supported.

Apparently the other user only tested on the first few channels and it worked there by chance.

**Pull request closed without merging**
