### PR TITLE
Add preset animations

### PR DESCRIPTION
**Pull request by pboyd04**
Add ability to provide preset animations to the web service

### CODE REVIEW

**Comment by bluemaex** [comment]
@pboyd04 Very cool - Do you have an example animation for the configuration so I can test this? (And it to the documentation)

**Comment by pboyd04** [comment]
@bluemaex My config is obviously different. Here is what I have in my config file:
```json
"animPresets": [
		{
			"label": "RGB",
			"anim": {
				"office": [
					{"to": {"2": 0, "3": 0, "4": 0}},
					{"to": {"2": 255}, "duration": 1000},
					{"to": {"3": 255}, "duration": 1000},
					{"to": {"4": 255}, "duration": 1000}
				]
			}
		}
	]
```
You should be able to take your example post and just add it. Something like:
```json
"animPresets": [{
		"label": "test",
		"anim": {
			"office": [{
					"to": {
						"10": 0,
						"20": 0
					}
				},
				{
					"to": {
						"10": 255
					},
					"duration": 2000
				},
				{
					"to": {
						"20": 255
					},
					"duration": 1000
				}
			]
		}
	}]
```

**Comment by bluemaex** [comment]
Nice, thank you, gonna have a look at it 👍

**Comment by bluemaex** [comment]
❤️

**Pull request merged**
